import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { testRender } from '@opentui/solid'
import App from '../../src/tui/components/App.jsx'

const fail = (message) => {
  throw new Error(message)
}

const createTestStorage = (dataFile) => readFile(dataFile, 'utf8').then(JSON.parse).then((initialSecrets) => {
  let secrets = initialSecrets
  const save = () => writeFile(dataFile, JSON.stringify(secrets, null, 2), 'utf8')

  return {
    getAll: () => secrets,
    create: (secret) => {
      secrets = [...secrets, secret]
      return save()
    },
    update: (key, updates) => {
      secrets = secrets.map((secret) => secret.key === key ? { ...secret, ...updates } : secret)
      return save()
    },
    delete: (key) => {
      secrets = secrets.filter((secret) => secret.key !== key)
      return save()
    }
  }
})

const expectFrame = (setup, text) => {
  if (!JSON.stringify(setup.captureSpans()).includes(text)) fail(`Expected TUI frame to include: ${text}`)
}

const testDirectory = await mkdtemp(path.join(os.tmpdir(), 'clavis-tui-smoke-'))
const dataFile = path.join(testDirectory, 'tokens.json')
const testSecrets = [{
  key: 'test.github.token',
  token: 'test-token-value',
  tag: 'test',
  comment: 'Generated by the TUI smoke test',
  expiration: null,
  sid: 1,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z'
}]

try {
  await writeFile(dataFile, JSON.stringify(testSecrets, null, 2), 'utf8')
  const storage = await createTestStorage(dataFile)

  const tableSetup = await testRender(() => <App secrets={storage.getAll()} storage={storage} />, { width: 80, height: 24 })
  await tableSetup.flush()
  expectFrame(tableSetup, 'test.github.token')
  tableSetup.mockInput.pressKey('q')
  if (!tableSetup.renderer.isDestroyed) fail('Expected q to destroy the renderer')

  const createSetup = await testRender(() => <App secrets={storage.getAll()} storage={storage} />, { width: 80, height: 24 })
  await createSetup.flush()
  createSetup.mockInput.pressKey('c')
  await createSetup.flush()
  expectFrame(createSetup, 'Create New Token')
  createSetup.renderer.destroy()

  console.log('TUI smoke test passed')
} finally {
  await rm(testDirectory, { recursive: true, force: true })
}
